{
    "name": "Ticketmaton - Sistema de Turnos",
    "version": "19.0.1.0.0",
    "summary": "Dispensador de turnos con kiosco, pantalla publica e impresion termica",
    "category": "Services",
    "author": "Custom",
    "license": "LGPL-3",
    "depends": ["base", "web", "bus", "website"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/ticketmaton_station_views.xml",
        "views/ticketmaton_queue_views.xml",
        "views/ticketmaton_ticket_views.xml",
        "views/ticketmaton_menus.xml",
        "views/ticketmaton_templates.xml",
        "report/ticket_report.xml",
        "data/demo_data.xml",
    ],
    "assets": {
        "cs_ticketmaton.assets_kiosk": [
            ("include", "web._assets_helpers"),
            ("include", "web._assets_frontend_helpers"),
            "web/static/lib/bootstrap/scss/_functions.scss",
            "web/static/lib/bootstrap/scss/_variables.scss",
            "web/static/lib/bootstrap/scss/_variables-dark.scss",
            "web/static/lib/bootstrap/scss/_maps.scss",
            ("include", "web._assets_bootstrap_frontend"),
            "cs_ticketmaton/static/src/css/kiosk.css",
            "cs_ticketmaton/static/src/css/print_thermal.css",
        ],
        "cs_ticketmaton.assets_display": [
            ("include", "web._assets_helpers"),
            ("include", "web._assets_frontend_helpers"),
            "web/static/lib/bootstrap/scss/_functions.scss",
            "web/static/lib/bootstrap/scss/_variables.scss",
            "web/static/lib/bootstrap/scss/_variables-dark.scss",
            "web/static/lib/bootstrap/scss/_maps.scss",
            ("include", "web._assets_bootstrap_frontend"),
            "cs_ticketmaton/static/src/css/display.css",
        ],
        "cs_ticketmaton.assets_control": [
            ("include", "web._assets_helpers"),
            ("include", "web._assets_frontend_helpers"),
            "web/static/lib/bootstrap/scss/_functions.scss",
            "web/static/lib/bootstrap/scss/_variables.scss",
            "web/static/lib/bootstrap/scss/_variables-dark.scss",
            "web/static/lib/bootstrap/scss/_maps.scss",
            ("include", "web._assets_bootstrap_frontend"),
            "cs_ticketmaton/static/src/css/control.css",
        ],
    },
    "application": True,
    "installable": True,
}
